### ISSUE TITLE
Placeholders are now labels

### ISSUE THREAD

**Issue by Piioo** [chrisdavies/jquery.placeholderlabels#3]
The newest version generates labels from placeholders in IE9 on Win7 and not placeholders.

**Comment by chrisdavies** [comment]
It seems to be working the way it's intended. Try pulling the latest and running sample.html. In browsers that don't support placeholder text, this library will insert a label instead of the placeholder. The sample.css file provides a demo of how that could be styled so that it looks and behaves similarly to placeholder.

But at this point, I no longer write projects for older browsers, so this library's usefulness to me personally has come and gone.

**Comment by jaffadog** [comment]
IE9 does not support placeholders natively.  this script does generate labels - and places them super-imposed over the inputs in order to simulate placeholder text.  It is dependent on the accompanying CSS to position and style the label properly.  Without the CSS, you get the effect you are reporting.
